baseURL = 'https://blog.ldbmcs.com/'
languageCode = 'zh'
author = "ldbmcs"
title = 'Just Once'
theme = "paper"
paginate = 10
enableInlineShortcodes = true

disqusShortname = 'ldbmcs'   # add disqus comments
[params]
    twitter = 'ldbmcs'
    github = 'ldbmcs'

    avatar = 'ldbmcs@gmail.com'
    name = 'ldbmcs'
    bio = 'Discover fresh context'
    rss = true                      # show rss icon with link

[menu]
    [[menu.main]]
        identifier = "about"
        name = "关于我"
        url = "/about/"
        weight = 10